import MainLayout from "@/components/layout/layout"
import { Suspense } from "react"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Suspense fallback={<div>Loading...</div>}>
      <MainLayout children={children} />
    </Suspense>
  )
}
