import { AuthProvider } from "@/components/auth/context"
import MainLayout from "@/components/layout/layout"

export const metadata = {
  title: "Trang chủ",
  description: "Generated by Next.js",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthProvider>
      <MainLayout children={children} />
    </AuthProvider>
  )
}
