import MainLayout from "@/components/layout"

export const metadata = {
  title: "Trang chủ",
  description: "Generated by Next.js",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <MainLayout children={children} />
}
