import { HomeWrapper } from "@/components/home"
export const metadata = {
  title: "Trang chủ | GenesisTalk",
  description: "Generated by Next.js",
}
export default function Home() {
  return <HomeWrapper />
}
