import { PostWrapper } from "@/components/post"

export const metadata = {
  title: "Danh sách bài viết | GenesisTalk",
  description: "Generated by Next.js",
}
export default function Post() {
  return <PostWrapper />
}
