import { PostForm } from "@/components/post/form"
export const metadata = {
  title: "Chỉnh sửa bài viết | GenesisTalk",
  description: "Generated by Next.js",
}
export default function Home() {
  return (
    <div className="container bg-white p-3 md:p-8 rounded-lg shadow-lg flex flex-col gap-8">
      <div className="text-center text-2xl">Chỉnh sửa bài viết</div>
      <PostForm />
    </div>
  )
}
