import { DetailPostWrapper } from "@/components/post/detail"
export const metadata = {
  title: "Bài viết | GenesisTalk",
  description: "Generated by Next.js",
}
export default function Home() {
  return <DetailPostWrapper />
}
