import { Metadata } from "next"
export const metadata: Metadata = {
  title: "Đăng nhập",
  description: "Generated by create next app",
}
export default function User() {
  return (
    <div className="bg-white max-h-[100%_-_30rem] h-full max-w-[32rem] w-full mx-auto rounded-2xl p-3 md:px-5 md:py-8 shadow-2xl">
      <div className="text-3xl font-bold text-center">Đăng nhập</div>
      <div></div>
    </div>
  )
}
