import SignInWrapper from "@/components/user/sign-in"
import { Metadata } from "next"
export const metadata: Metadata = {
  title: "Đăng nhập",
  description: "Generated by create next app",
}
export default function User() {
  return <SignInWrapper />
}
